# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcb230cb1e8357ec590c3367e56a4f8115e483ee70e93e60658e730c9f6c5a67521252a2c96238f2510a4580f28b531ccb0033c6155c18af8312b9a673fbfa16

test:
  secret_key_base: 1bf4ffc009e391b6e0cecc1a0aee482dce128c101ad0fbab5845345a3a3defa2954e9a1ec19394f8e36391d2abd4b771d8218a0f77066ea3770865c61e234bed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
